export const assets ={
    santafe:"./imgsantafe/puente-colgante.jpg",
    Alfajor:"./imgsantafe/alfajor.png" ,
    Basilica:"./imgsantafe/basilica.png" ,
    Bichofeo:"./imgsantafe/bichofeo.png" ,
    Brigadier:"./imgsantafe/brigadier.png" ,
    Carpincho:"./imgsantafe/carpincho.jpg",
    Costanera:"./imgsantafe/costa.png" ,
    Colon:"./imgsantafe/colon.png",
    Union:"./imgsantafe/union.png",
    CasaGobierno:"./imgsantafe/casag.png",
    Liso:"./imgsantafe/liso.png",
    Faro:"./imgsantafe/faro.png",
    Monzon:"./imgsantafe/monzon.png",
    Museo:"./imgsantafe/museo.png",
    Pescador:"./imgsantafe/mpescador.png",
    Peatonal:"./imgsantafe/peatonal.png",
    Puente:"./imgsantafe/puente.png",
    Puerto:"./imgsantafe/puerto.png",
    Quincho:"./imgsantafe/quincho.png",
    Redonda:"./imgsantafe/redonda.png",
    Municipalidad:"./imgsantafe/muni.png",
    santa:"./imgsantafe/santafe.jpg"
}

